import { IAsyncEnumerable } from "../async/IAsyncEnumerable";
import { IComparer, IConstructor, IEqualityComparer, IGrouping, ITuple } from "../shared/shared";
import { IOrderedParallelEnumerable } from "./IOrderedParallelEnumerable";
import { IParallelEnumerable } from "./IParallelEnumerable";
export declare class BasicParallelEnumerable<TSource> implements IParallelEnumerable<TSource> {
    private readonly dataFunc;
    constructor(promise: () => Promise<TSource[]>);
    constructor(dataFunc: () => Array<Promise<TSource>>);
    aggregate(func: (x: TSource, y: TSource) => TSource): Promise<TSource>;
    aggregate<TAccumulate>(seed: TAccumulate, func: (x: TAccumulate, y: TSource) => TAccumulate): Promise<TAccumulate>;
    aggregate<TAccumulate, TResult>(seed: TAccumulate, func: (x: TAccumulate, y: TSource) => TAccumulate, resultSelector: (x: TAccumulate) => TResult): Promise<TResult>;
    all(predicate: (x: TSource) => boolean): Promise<boolean>;
    any(predicate?: (x: TSource) => boolean): Promise<boolean>;
    average(this: IParallelEnumerable<number>): Promise<number>;
    average(selector: (x: TSource) => number): Promise<number>;
    concat(second: IParallelEnumerable<TSource> | IAsyncEnumerable<TSource>): IParallelEnumerable<TSource>;
    contains(value: TSource, comparer?: IEqualityComparer<TSource>): Promise<boolean>;
    count(predicate?: (x: TSource) => boolean): Promise<number>;
    distinct(comparer?: IEqualityComparer<TSource>): IParallelEnumerable<TSource>;
    each(action: (x: TSource) => void): IParallelEnumerable<TSource>;
    elementAt(index: number): Promise<TSource>;
    elementAtOrDefault(index: number): Promise<TSource | null>;
    except(second: IParallelEnumerable<TSource> | IAsyncEnumerable<TSource>, comparer?: IEqualityComparer<TSource>): IParallelEnumerable<TSource>;
    first(predicate?: (x: TSource) => boolean): Promise<TSource>;
    private first_1();
    private first_2(predicate);
    firstOrDefault(predicate?: (x: TSource) => boolean): Promise<TSource | null>;
    private firstOrDefault_1();
    private firstOrDefault_2(predicate);
    groupBy(keySelector: (x: TSource) => number): IParallelEnumerable<IGrouping<number, TSource>>;
    groupBy(keySelector: (x: TSource) => string): IParallelEnumerable<IGrouping<string, TSource>>;
    groupBy<TKey>(keySelector: (x: TSource) => TKey, comparer: IEqualityComparer<TKey>): IParallelEnumerable<IGrouping<TKey, TSource>>;
    groupByWithSel<TElement>(keySelector: (x: TSource) => number, elementSelector: (x: TSource) => TElement): IParallelEnumerable<IGrouping<number, TElement>>;
    groupByWithSel<TElement>(keySelector: (x: TSource) => string, elementSelector: (x: TSource) => TElement): IParallelEnumerable<IGrouping<string, TElement>>;
    groupByWithSel<TKey, TElement>(keySelector: (x: TSource) => TKey, elementSelector: (x: TSource) => TElement, comparer: IEqualityComparer<TKey>): IParallelEnumerable<IGrouping<TKey, TElement>>;
    intersect(second: IParallelEnumerable<TSource> | IAsyncEnumerable<TSource>, comparer?: IEqualityComparer<TSource>): IParallelEnumerable<TSource>;
    joinByKey<TInner, TKey, TResult>(inner: IAsyncEnumerable<TInner> | IParallelEnumerable<TInner>, outerKeySelector: (x: TSource) => TKey, innerKeySelector: (x: TInner) => TKey, resultSelector: (x: TSource, y: TInner) => TResult, comparer?: IEqualityComparer<TKey>): IParallelEnumerable<TResult>;
    last(predicate?: (x: TSource) => boolean): Promise<TSource>;
    lastOrDefault(predicate?: (x: TSource) => boolean): Promise<TSource | null>;
    max(this: IParallelEnumerable<number>): Promise<number>;
    max(selector: (x: TSource) => number): Promise<number>;
    min(this: IParallelEnumerable<number>): Promise<number>;
    min(selector: (x: TSource) => number): Promise<number>;
    ofType(type: "object"): IParallelEnumerable<Object>;
    ofType(type: "function"): IParallelEnumerable<Function>;
    ofType(type: "symbol"): IParallelEnumerable<Symbol>;
    ofType(type: "boolean"): IParallelEnumerable<boolean>;
    ofType(type: "number"): IParallelEnumerable<number>;
    ofType(type: "string"): IParallelEnumerable<string>;
    ofType<TResult>(type: IConstructor<TResult>): IParallelEnumerable<TResult>;
    orderBy(predicate: (x: TSource) => string | number): IParallelEnumerable<TSource>;
    orderBy(predicate: (x: TSource) => number, comparer: IComparer<number>): IParallelEnumerable<TSource>;
    orderBy(predicate: (x: TSource) => string, comparer: IComparer<string>): IParallelEnumerable<TSource>;
    orderByDescending(predicate: (x: TSource) => string | number): IParallelEnumerable<TSource>;
    orderByDescending(predicate: (x: TSource) => number, comparer: IComparer<number>): IParallelEnumerable<TSource>;
    orderByDescending(predicate: (x: TSource) => string, comparer: IComparer<string>): IParallelEnumerable<TSource>;
    reverse(): IParallelEnumerable<TSource>;
    select<OUT>(selector: (x: TSource) => OUT): IParallelEnumerable<OUT>;
    select<TKey extends keyof TSource>(key: TKey): IParallelEnumerable<TSource[TKey]>;
    selectMany<OUT>(selector: (x: TSource) => Iterable<OUT>): IParallelEnumerable<OUT>;
    selectMany<TBindedSource extends {
        [key: string]: Iterable<TOut>;
    }, TOut>(this: IParallelEnumerable<TBindedSource>, selector: keyof TBindedSource): IParallelEnumerable<TOut>;
    sequenceEquals(second: IParallelEnumerable<TSource> | IAsyncEnumerable<TSource>, comparer?: IEqualityComparer<TSource>): Promise<boolean>;
    single(predicate?: (x: TSource) => boolean): Promise<TSource>;
    private single_1();
    private single_2(predicate);
    singleOrDefault(predicate?: (x: TSource) => boolean): Promise<TSource | null>;
    private singleOrDefault_1();
    private singleOrDefault_2(predicate);
    skip(count: number): IParallelEnumerable<TSource>;
    skipWhile(predicate: (x: TSource, index: number) => boolean): IParallelEnumerable<TSource>;
    sum(this: IParallelEnumerable<number>): Promise<number>;
    sum(this: IParallelEnumerable<TSource>, selector: (x: TSource) => number): Promise<number>;
    take(amount: number): IParallelEnumerable<TSource>;
    takeWhile(predicate: (x: TSource, index: number) => boolean): IParallelEnumerable<TSource>;
    toArray(): Promise<TSource[]>;
    toMap<TKey>(selector: (x: TSource) => TKey): Promise<Map<TKey, TSource[]>>;
    toSet(): Promise<Set<TSource>>;
    union(second: IParallelEnumerable<TSource> | IAsyncEnumerable<TSource>, comparer?: IEqualityComparer<TSource>): IParallelEnumerable<TSource>;
    where(predicate: (x: TSource, index: number) => boolean): IParallelEnumerable<TSource>;
    zip<TSecond, TResult>(second: IParallelEnumerable<TSource> | IAsyncEnumerable<TSecond>, resultSelector: (x: TSource, y: TSecond) => TResult): IParallelEnumerable<TResult>;
    zip<TSecond>(second: IAsyncEnumerable<TSecond> | IParallelEnumerable<TSecond>): IParallelEnumerable<ITuple<TSource, TSecond>>;
    private nextIteration<TOut>(onfulfilled);
    [Symbol.asyncIterator](): AsyncIterableIterator<TSource>;
}
export declare class ParallelEnumerable {
    private constructor();
    static aggregate<TSource>(source: AsyncIterable<TSource>, func: (x: TSource, y: TSource) => TSource): Promise<TSource>;
    static aggregate<TSource, TAccumulate>(source: AsyncIterable<TSource>, seed: TAccumulate, func: (x: TAccumulate, y: TSource) => TAccumulate): Promise<TAccumulate>;
    static aggregate<TSource, TAccumulate, TResult>(source: AsyncIterable<TSource>, seed: TAccumulate, func: (x: TAccumulate, y: TSource) => TAccumulate, resultSelector: (x: TAccumulate) => TResult): Promise<TResult>;
    private static aggregate_1<TSource>(source, func);
    private static aggregate_2<TSource, TAccumulate>(source, seed, func);
    private static aggregate_3<TSource, TAccumulate, TResult>(source, seed, func, resultSelector);
    static average(source: IAsyncEnumerable<number>): Promise<number>;
    static average<TSource>(source: IAsyncEnumerable<TSource>, selector: (x: TSource) => number): Promise<number>;
    private static average_1(source);
    private static average_2<TSource>(source, func);
    static except<TSource>(first: IParallelEnumerable<TSource>, second: IParallelEnumerable<TSource> | IAsyncEnumerable<TSource>, comparer?: IEqualityComparer<TSource>): IParallelEnumerable<TSource>;
    static flatten<TSource>(source: IParallelEnumerable<TSource | IParallelEnumerable<TSource>>): IParallelEnumerable<TSource>;
    static flatten<TSource>(source: IParallelEnumerable<TSource | IParallelEnumerable<TSource>>, shallow: false): IParallelEnumerable<TSource>;
    static flatten<TSource>(source: IParallelEnumerable<TSource | IParallelEnumerable<TSource>>, shallow: true): IParallelEnumerable<TSource | AsyncIterable<TSource>>;
    static from<TSource>(promises: Array<Promise<TSource>>): IParallelEnumerable<TSource>;
    static from<TSource>(generator: () => Promise<TSource[]>): IParallelEnumerable<TSource>;
    static from<TSource>(generator: () => Array<Promise<TSource>>): IParallelEnumerable<TSource>;
    static groupBy<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, keySelector: (x: TSource) => number): IAsyncEnumerable<IGrouping<number, TSource>>;
    static groupBy<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, keySelector: (x: TSource) => string): IAsyncEnumerable<IGrouping<string, TSource>>;
    static groupBy<TSource, TKey>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, keySelector: (x: TSource) => TKey, comparer: IEqualityComparer<TKey>): IAsyncEnumerable<IGrouping<TKey, TSource>>;
    private static groupBy_0_Simple<TSource>(source, keySelector);
    private static groupBy_0<TSource, TKey>(source, keySelector, comparer);
    static groupByWithSel<TSource, TElement>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, keySelector: ((x: TSource) => number), elementSelector: (x: TSource) => TElement): IParallelEnumerable<IGrouping<number, TElement>>;
    static groupByWithSel<TSource, TElement>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, keySelector: ((x: TSource) => string), elementSelector: (x: TSource) => TElement): IParallelEnumerable<IGrouping<string, TElement>>;
    static groupByWithSel<TSource, TKey, TElement>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, keySelector: ((x: TSource) => TKey), elementSelector: (x: TSource) => TElement, comparer: IEqualityComparer<TKey>): IParallelEnumerable<IGrouping<TKey, TElement>>;
    private static groupBy_1_Simple<TSource, TElement>(source, keySelector, elementSelector);
    private static groupBy_1<TSource, TKey, TElement>(source, keySelector, elementSelector, comparer);
    static join<TOuter, TInner, TKey, TResult>(outer: IAsyncEnumerable<TOuter> | IParallelEnumerable<TOuter>, inner: IAsyncEnumerable<TInner> | IParallelEnumerable<TInner>, outerKeySelector: (x: TOuter) => TKey, innerKeySelector: (x: TInner) => TKey, resultSelector: (x: TOuter, y: TInner) => TResult): IParallelEnumerable<TResult>;
    static join<TOuter, TInner, TKey, TResult>(outer: IAsyncEnumerable<TOuter> | IParallelEnumerable<TOuter>, inner: IAsyncEnumerable<TInner> | IParallelEnumerable<TInner>, outerKeySelector: (x: TOuter) => TKey, innerKeySelector: (x: TInner) => TKey, resultSelector: (x: TOuter, y: TInner) => TResult, comparer: IEqualityComparer<TKey>): IParallelEnumerable<TResult>;
    static intersect<TSource>(first: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, second: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, comparer?: IEqualityComparer<TSource>): IParallelEnumerable<TSource>;
    static skip<TSource>(source: IParallelEnumerable<TSource>, count: number): IParallelEnumerable<TSource>;
    static skipWhile<TSource>(source: IParallelEnumerable<TSource>, predicate: (x: TSource, index: number) => boolean): IParallelEnumerable<TSource>;
    static ofType<TSource, TResult>(source: IParallelEnumerable<TSource> | IAsyncEnumerable<TSource>, type?: IConstructor<TResult> | string): IParallelEnumerable<TResult>;
    static orderBy<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, keySelector: (x: TSource) => string): IOrderedParallelEnumerable<TSource>;
    static orderBy<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, keySelector: (x: TSource) => string, comparer: IComparer<string>): IOrderedParallelEnumerable<TSource>;
    static orderBy<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, keySelector: (x: TSource) => number): IOrderedParallelEnumerable<TSource>;
    static orderBy<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, keySelector: (x: TSource) => number, comparer: IComparer<number>): IOrderedParallelEnumerable<TSource>;
    private static orderByInner<TSource>(source, keySelector);
    static orderByDescending<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, keySelector: (x: TSource) => string): IOrderedParallelEnumerable<TSource>;
    static orderByDescending<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, keySelector: (x: TSource) => string, comparer: IComparer<string>): IOrderedParallelEnumerable<TSource>;
    static orderByDescending<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, keySelector: (x: TSource) => number): IOrderedParallelEnumerable<TSource>;
    static orderByDescending<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, keySelector: (x: TSource) => number, comparer: IComparer<number>): IOrderedParallelEnumerable<TSource>;
    static range(start: number, count: number): IParallelEnumerable<number>;
    static repeat<T>(element: T, count: number, delay?: number): IParallelEnumerable<T>;
    private static repeat_1<T>(element, count);
    private static repeat_2<T>(element, count, delay);
    static reverse<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>): IParallelEnumerable<TSource>;
    static sequenceEquals<TSource>(first: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, second: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, comparer?: IEqualityComparer<TSource>): Promise<boolean>;
    static sum(source: IAsyncEnumerable<number> | IParallelEnumerable<number>): Promise<number>;
    static sum<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, selector: (x: TSource) => number): Promise<number>;
    private static sum_1(source);
    private static sum_2<TSource>(source, selector);
    static take<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, amount: number): IParallelEnumerable<TSource>;
    static takeWhile<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, predicate: (x: TSource, index: number) => boolean): IParallelEnumerable<TSource>;
    static thenBy<TSource>(source: IOrderedParallelEnumerable<TSource>, keySelector: (x: TSource) => string): IOrderedParallelEnumerable<TSource>;
    static thenBy<TSource>(source: IOrderedParallelEnumerable<TSource>, keySelector: (x: TSource) => string, comparer: IComparer<string>): IOrderedParallelEnumerable<TSource>;
    static thenBy<TSource>(source: IOrderedParallelEnumerable<TSource>, keySelector: (x: TSource) => number): IOrderedParallelEnumerable<TSource>;
    static thenBy<TSource>(source: IOrderedParallelEnumerable<TSource>, keySelector: (x: TSource) => number, comparer: IComparer<number>): IOrderedParallelEnumerable<TSource>;
    static thenByDescending<TSource>(source: IOrderedParallelEnumerable<TSource>, keySelector: (x: TSource) => string): IOrderedParallelEnumerable<TSource>;
    static thenByDescending<TSource>(source: IOrderedParallelEnumerable<TSource>, keySelector: (x: TSource) => string, comparer: IComparer<string>): IOrderedParallelEnumerable<TSource>;
    static thenByDescending<TSource>(source: IOrderedParallelEnumerable<TSource>, keySelector: (x: TSource) => number): IOrderedParallelEnumerable<TSource>;
    static thenByDescending<TSource>(source: IOrderedParallelEnumerable<TSource>, keySelector: (x: TSource) => number, comparer: IComparer<number>): IOrderedParallelEnumerable<TSource>;
    static toMap<K, V>(source: IAsyncEnumerable<V> | IParallelEnumerable<V>, selector: (x: V) => K): Promise<Map<K, V[]>>;
    static toObject<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>, selector: (x: TSource) => string): Promise<{
        [key: string]: TSource;
    }>;
    static toSet<TSource>(source: IAsyncEnumerable<TSource> | IParallelEnumerable<TSource>): Promise<Set<TSource>>;
    static union<TSource>(first: IParallelEnumerable<TSource>, second: IParallelEnumerable<TSource> | IAsyncEnumerable<TSource>, comparer?: IEqualityComparer<TSource>): IParallelEnumerable<TSource>;
    private static union_1<TSource>(first, second);
    private static union_2<TSource>(first, second, comparer);
    static zip<T, Y>(source: IAsyncEnumerable<T>, second: IAsyncEnumerable<Y>): IParallelEnumerable<ITuple<T, Y>>;
    static zip<T, Y, OUT>(source: IAsyncEnumerable<T>, second: IAsyncEnumerable<Y>, resultSelector: (x: T, y: Y) => OUT): IParallelEnumerable<OUT>;
    private static zip_1<T, Y>(source, second);
    private static zip_2<T, Y, OUT>(source, second, resultSelector);
}
