name: LinqToTypeScript

trigger:
  - master
  - InDev

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    node_12_x:
      node_version: 12.x
    node_14_x:
      node_version: 14.x
    node_15_x:
      node_version: 15.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- script: |
    npm install -g typescript jest
  displayName: 'Install Globals'
- script: |
    npm install
    npm run build
  displayName: 'Build Library'
- script: npm run lint
  displayName: 'Run Lint'
- script: |
    cd test
    npm install
    npm run test
  displayName: 'Run Tests'
- script: |
    cd nodetest
    npm install
    tsc
    node index.js
  displayName: 'Test Node'
- script: |
    cd reacttest
    npm install
    npm run build
  displayName: 'Test React'
- script: |
    cd examples
    npm install
    npm run test
  displayName: 'Test Examples'