name: LinqToTypeScript

trigger:
  - master
  - InDev

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 18.x

- script: |
    npm install -g typescript jest typedoc
  displayName: 'Install Globals'
- script: |
    npm install
    npm run build
  displayName: 'Build Library'
- script: npm run lint
  displayName: 'Run Lint'
- script: npm run doc
  displayName: 'Run Type Doc'
- script: |
    cd tests/unittests
    npm install
    npm run test
  displayName: 'Run Unit Tests'
- script: |
    cd tests/nodetest
    npm install
    tsc
    node index.js
  displayName: 'Test Node'
- script: |
    cd tests/reacttest
    npm install
    npm run build
  displayName: 'Test React'
- script: |
    cd tests/moduletest
    npm install
    tsc
    node index.js
  displayName: 'Test Modules'
- script: |
    cd tests/esmtest
    npm install
    tsc
    node index.js
  displayName: 'Test ESM Modules'
- script: |
    cd examples
    npm install
    npm run test
  displayName: 'Test Examples'