name: LinqToTypeScript

trigger:
  - master
  - InDev

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    node_16_x:
      node_version: 16.x
    node_17_x:
      node_version: 17.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- script: |
    npm install -g typescript jest typedoc
  displayName: 'Install Globals'
- script: |
    npm install
    npm run build
  displayName: 'Build Library'
- script: npm run lint
  displayName: 'Run Lint'
- script: npm run doc
  displayName: 'Run Type Doc'
- script: |
    cd tests/unittests
    npm install
    npm run test
  displayName: 'Run Unit Tests'
- script: |
    cd tests/nodetest
    npm install
    tsc
    node index.js
  displayName: 'Test Node'
- script: |
    cd tests/reacttest
    npm install
    npm run build
  displayName: 'Test React'
- script: |
    cd tests/moduletest
    npm install
    tsc
    node --experimental-specifier-resolution=node index.js
  displayName: 'Test ES6 Modules'
- script: |
    cd examples
    npm install
    npm run test
  displayName: 'Test Examples'