name: LinqToTypeScriptInDev

trigger:
  - InDev

pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    node_10_x:
      node_version: 10.x
    node_12_x:
      node_version: 12.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

- script: |
    npm install -g typescript tslint@5.12.1 jest rollup
  displayName: 'Install Globals'
- script: |
    npm install
    npm run build
  displayName: 'Build Library'
- script: tslint -p ./
  displayName: 'Run Lint'
- script: |
    cd test
    npm install
    npm run test
  displayName: 'Run Tests'