name: LinqToTypeScript

trigger:
  - master
  - InDev

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: 20.x
    checkLatest: true
- powershell: |
    npm install -g typescript jest typedoc
  displayName: 'Install Globals'
  failOnStderr: true
- powershell: |
    npm install
    npm run build
  displayName: 'Build Library'
  failOnStderr: true
- script: npm run lint
  displayName: 'Run Lint'
  failOnStderr: true
- powershell: |
    npm run doc
  displayName: 'Run Type Doc'
  failOnStderr: true
- powershell: |
    cd tests/unittests
    npm install
    npm run test
  displayName: 'Run Unit Tests'
  failOnStderr: false
  continueOnError: false
- powershell: |
    cd tests/nodetest
    npm install
    tsc
    node index.js
  displayName: 'Test Node'
  failOnStderr: true
- powershell: |
    cd tests/reacttest
    npm install
    npm run build
  displayName: 'Test React'
  failOnStderr: true
- powershell: |
    cd tests/moduletest
    npm install
    tsc
    node index.js
  displayName: 'Test Modules'
  failOnStderr: true
- powershell: |
    cd tests/esmtest
    npm install
    tsc
    node index.js
  displayName: 'Test ESM Modules'
  failOnStderr: true
- powershell: |
    cd examples
    npm install
    npm run test
  displayName: 'Test Examples'
  failOnStderr: true