"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var TypesAndHelpers_1 = require("./TypesAndHelpers");
exports.ArgumentOutOfRangeException = TypesAndHelpers_1.ArgumentOutOfRangeException;
exports.AsTuple = TypesAndHelpers_1.AsTuple;
exports.EqualityComparer = TypesAndHelpers_1.EqualityComparer;
exports.ErrorString = TypesAndHelpers_1.ErrorString;
exports.InvalidOperationException = TypesAndHelpers_1.InvalidOperationException;
exports.NumberComparer = TypesAndHelpers_1.NumberComparer;
exports.StrictEqualityComparer = TypesAndHelpers_1.StrictEqualityComparer;
exports.StringifyComparer = TypesAndHelpers_1.StringifyComparer;
